#!/bin/bash

export PORT=9000
export HOSTNAME=0.0.0.0
export NODE_ENV=production
export CLOUDBASE_HTTP_FUNCTION=1

exec /var/lang/node20/bin/node node_modules/next/dist/bin/next start --hostname 0.0.0.0 --port 9000
